#http://localhost/api/v1/swagger-ui/index.html
server:
  port: 80
  servlet:
    context-path: /api/v1
    encoding:
      charset: UTF-8
spring:
  datasource:
    hikari:
      minimum-idle: 5
      maximum-pool-size: 24
      idle-timeout: 45000
    jpa:
      properties:
        hibernate:
          cache:
            use_second_level_cache: false
            store_mode: bypass
    username: ''
    password: ''
    url: ''
    driver-class-name: org.postgresql.Driver